development:
  adapter: mysql
  encoding: utf8
  database: yuno_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: yuno_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: yuno_production
  username: root
  password: root
  host: localhost

#development:
 # adapter: sqlite3
 # database: db/development.sqlite3
 # timeout: 5000

#test:
 # adapter: sqlite3
 # database: db/test.sqlite3
 # timeout: 5000

#production:
 # adapter: sqlite3
 # database: db/production.sqlite3
 # timeout: 5000
